[package]
name = "rustyshell"
version = "0.1.0"
authors = ["Matt Ward <matt@wardm.uk>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
